//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTHUCUNGEntities : DbContext
    {
        public QUANLYTHUCUNGEntities()
            : base("name=QUANLYTHUCUNGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<THUCUNG2> THUCUNG2 { get; set; }
    }
}
