//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public int MAKH { get; set; }
        public string TENKH { get; set; }
        public int MATHUCUNG { get; set; }
    
        public virtual THUCUNG2 THUCUNG2 { get; set; }
    }
}
