//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCUNG2
    {
        public THUCUNG2()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public int MATHUCUNG { get; set; }
        public string TENTHUCUNG { get; set; }
        public string TUOITC { get; set; }
        public string GIOITINH { get; set; }
        public string LOAI { get; set; }
    
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
