#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeTai.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_ThuCung")]
	public partial class dbQuanLyThuCungDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertCHITIETSANPHAM(CHITIETSANPHAM instance);
    partial void UpdateCHITIETSANPHAM(CHITIETSANPHAM instance);
    partial void DeleteCHITIETSANPHAM(CHITIETSANPHAM instance);
    partial void InsertCHITIETTHUCUNG(CHITIETTHUCUNG instance);
    partial void UpdateCHITIETTHUCUNG(CHITIETTHUCUNG instance);
    partial void DeleteCHITIETTHUCUNG(CHITIETTHUCUNG instance);
    partial void InsertHOA_DON(HOA_DON instance);
    partial void UpdateHOA_DON(HOA_DON instance);
    partial void DeleteHOA_DON(HOA_DON instance);
    partial void InsertKHACH(KHACH instance);
    partial void UpdateKHACH(KHACH instance);
    partial void DeleteKHACH(KHACH instance);
    partial void InsertSANPHAM(SANPHAM instance);
    partial void UpdateSANPHAM(SANPHAM instance);
    partial void DeleteSANPHAM(SANPHAM instance);
    partial void InsertTHU_CUNG(THU_CUNG instance);
    partial void UpdateTHU_CUNG(THU_CUNG instance);
    partial void DeleteTHU_CUNG(THU_CUNG instance);
    #endregion
		
		public dbQuanLyThuCungDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QL_ThuCungConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyThuCungDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyThuCungDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyThuCungDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQuanLyThuCungDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHD> CHITIETHDs
		{
			get
			{
				return this.GetTable<CHITIETHD>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETSANPHAM> CHITIETSANPHAMs
		{
			get
			{
				return this.GetTable<CHITIETSANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETTHUCUNG> CHITIETTHUCUNGs
		{
			get
			{
				return this.GetTable<CHITIETTHUCUNG>();
			}
		}
		
		public System.Data.Linq.Table<HOA_DON> HOA_DONs
		{
			get
			{
				return this.GetTable<HOA_DON>();
			}
		}
		
		public System.Data.Linq.Table<KHACH> KHACHes
		{
			get
			{
				return this.GetTable<KHACH>();
			}
		}
		
		public System.Data.Linq.Table<SANPHAM> SANPHAMs
		{
			get
			{
				return this.GetTable<SANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<THU_CUNG> THU_CUNGs
		{
			get
			{
				return this.GetTable<THU_CUNG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHD")]
	public partial class CHITIETHD
	{
		
		private string _MAHD;
		
		private int _MAKH;
		
		private string _MATHUCUNG;
		
		private string _MASP;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _TongTien;
		
		public CHITIETHD()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					this._MAHD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Int NOT NULL")]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this._MAKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCUNG", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MATHUCUNG
		{
			get
			{
				return this._MATHUCUNG;
			}
			set
			{
				if ((this._MATHUCUNG != value))
				{
					this._MATHUCUNG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASP", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MASP
		{
			get
			{
				return this._MASP;
			}
			set
			{
				if ((this._MASP != value))
				{
					this._MASP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETSANPHAM")]
	public partial class CHITIETSANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MoTa;
		
		private string _HINHSP;
		
		private string _HuongDanSuDung;
		
		private string _ThanhPhanDinhDuong;
		
		private string _ThuongHieu;
		
		private System.Nullable<int> _Gia;
		
		private string _KhoiLuong;
		
		private string _MASP;
		
		private EntityRef<SANPHAM> _SANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnHINHSPChanging(string value);
    partial void OnHINHSPChanged();
    partial void OnHuongDanSuDungChanging(string value);
    partial void OnHuongDanSuDungChanged();
    partial void OnThanhPhanDinhDuongChanging(string value);
    partial void OnThanhPhanDinhDuongChanged();
    partial void OnThuongHieuChanging(string value);
    partial void OnThuongHieuChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnKhoiLuongChanging(string value);
    partial void OnKhoiLuongChanged();
    partial void OnMASPChanging(string value);
    partial void OnMASPChanged();
    #endregion
		
		public CHITIETSANPHAM()
		{
			this._SANPHAM = default(EntityRef<SANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHSP", DbType="NVarChar(20)")]
		public string HINHSP
		{
			get
			{
				return this._HINHSP;
			}
			set
			{
				if ((this._HINHSP != value))
				{
					this.OnHINHSPChanging(value);
					this.SendPropertyChanging();
					this._HINHSP = value;
					this.SendPropertyChanged("HINHSP");
					this.OnHINHSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HuongDanSuDung", DbType="NVarChar(MAX)")]
		public string HuongDanSuDung
		{
			get
			{
				return this._HuongDanSuDung;
			}
			set
			{
				if ((this._HuongDanSuDung != value))
				{
					this.OnHuongDanSuDungChanging(value);
					this.SendPropertyChanging();
					this._HuongDanSuDung = value;
					this.SendPropertyChanged("HuongDanSuDung");
					this.OnHuongDanSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhPhanDinhDuong", DbType="NVarChar(MAX)")]
		public string ThanhPhanDinhDuong
		{
			get
			{
				return this._ThanhPhanDinhDuong;
			}
			set
			{
				if ((this._ThanhPhanDinhDuong != value))
				{
					this.OnThanhPhanDinhDuongChanging(value);
					this.SendPropertyChanging();
					this._ThanhPhanDinhDuong = value;
					this.SendPropertyChanged("ThanhPhanDinhDuong");
					this.OnThanhPhanDinhDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuongHieu", DbType="NVarChar(30)")]
		public string ThuongHieu
		{
			get
			{
				return this._ThuongHieu;
			}
			set
			{
				if ((this._ThuongHieu != value))
				{
					this.OnThuongHieuChanging(value);
					this.SendPropertyChanging();
					this._ThuongHieu = value;
					this.SendPropertyChanged("ThuongHieu");
					this.OnThuongHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiLuong", DbType="NVarChar(30)")]
		public string KhoiLuong
		{
			get
			{
				return this._KhoiLuong;
			}
			set
			{
				if ((this._KhoiLuong != value))
				{
					this.OnKhoiLuongChanging(value);
					this.SendPropertyChanging();
					this._KhoiLuong = value;
					this.SendPropertyChanged("KhoiLuong");
					this.OnKhoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASP
		{
			get
			{
				return this._MASP;
			}
			set
			{
				if ((this._MASP != value))
				{
					if (this._SANPHAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMASPChanging(value);
					this.SendPropertyChanging();
					this._MASP = value;
					this.SendPropertyChanged("MASP");
					this.OnMASPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CHITIETSANPHAM", Storage="_SANPHAM", ThisKey="MASP", OtherKey="MASP", IsForeignKey=true)]
		public SANPHAM SANPHAM
		{
			get
			{
				return this._SANPHAM.Entity;
			}
			set
			{
				SANPHAM previousValue = this._SANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._SANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SANPHAM.Entity = null;
						previousValue.CHITIETSANPHAM = null;
					}
					this._SANPHAM.Entity = value;
					if ((value != null))
					{
						value.CHITIETSANPHAM = this;
						this._MASP = value.MASP;
					}
					else
					{
						this._MASP = default(string);
					}
					this.SendPropertyChanged("SANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETTHUCUNG")]
	public partial class CHITIETTHUCUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GioiThieu;
		
		private string _HINHTC;
		
		private string _NguonGoc;
		
		private string _MATHUCUNG;
		
		private string _GIONGTC;
		
		private EntityRef<THU_CUNG> _THU_CUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGioiThieuChanging(string value);
    partial void OnGioiThieuChanged();
    partial void OnHINHTCChanging(string value);
    partial void OnHINHTCChanged();
    partial void OnNguonGocChanging(string value);
    partial void OnNguonGocChanged();
    partial void OnMATHUCUNGChanging(string value);
    partial void OnMATHUCUNGChanged();
    partial void OnGIONGTCChanging(string value);
    partial void OnGIONGTCChanged();
    #endregion
		
		public CHITIETTHUCUNG()
		{
			this._THU_CUNG = default(EntityRef<THU_CUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiThieu", DbType="NVarChar(100)")]
		public string GioiThieu
		{
			get
			{
				return this._GioiThieu;
			}
			set
			{
				if ((this._GioiThieu != value))
				{
					this.OnGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._GioiThieu = value;
					this.SendPropertyChanged("GioiThieu");
					this.OnGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHTC", DbType="NVarChar(20)")]
		public string HINHTC
		{
			get
			{
				return this._HINHTC;
			}
			set
			{
				if ((this._HINHTC != value))
				{
					this.OnHINHTCChanging(value);
					this.SendPropertyChanging();
					this._HINHTC = value;
					this.SendPropertyChanged("HINHTC");
					this.OnHINHTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguonGoc", DbType="NVarChar(MAX)")]
		public string NguonGoc
		{
			get
			{
				return this._NguonGoc;
			}
			set
			{
				if ((this._NguonGoc != value))
				{
					this.OnNguonGocChanging(value);
					this.SendPropertyChanging();
					this._NguonGoc = value;
					this.SendPropertyChanged("NguonGoc");
					this.OnNguonGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCUNG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUCUNG
		{
			get
			{
				return this._MATHUCUNG;
			}
			set
			{
				if ((this._MATHUCUNG != value))
				{
					if (this._THU_CUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUCUNGChanging(value);
					this.SendPropertyChanging();
					this._MATHUCUNG = value;
					this.SendPropertyChanged("MATHUCUNG");
					this.OnMATHUCUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIONGTC", DbType="NVarChar(50)")]
		public string GIONGTC
		{
			get
			{
				return this._GIONGTC;
			}
			set
			{
				if ((this._GIONGTC != value))
				{
					this.OnGIONGTCChanging(value);
					this.SendPropertyChanging();
					this._GIONGTC = value;
					this.SendPropertyChanged("GIONGTC");
					this.OnGIONGTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THU_CUNG_CHITIETTHUCUNG", Storage="_THU_CUNG", ThisKey="MATHUCUNG", OtherKey="MATHUCUNG", IsForeignKey=true)]
		public THU_CUNG THU_CUNG
		{
			get
			{
				return this._THU_CUNG.Entity;
			}
			set
			{
				THU_CUNG previousValue = this._THU_CUNG.Entity;
				if (((previousValue != value) 
							|| (this._THU_CUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THU_CUNG.Entity = null;
						previousValue.CHITIETTHUCUNG = null;
					}
					this._THU_CUNG.Entity = value;
					if ((value != null))
					{
						value.CHITIETTHUCUNG = this;
						this._MATHUCUNG = value.MATHUCUNG;
					}
					else
					{
						this._MATHUCUNG = default(string);
					}
					this.SendPropertyChanged("THU_CUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOA_DON")]
	public partial class HOA_DON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHD;
		
		private string _TENHD;
		
		private string _LOAIHD;
		
		private int _MAKH;
		
		private EntityRef<KHACH> _KHACH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(string value);
    partial void OnMAHDChanged();
    partial void OnTENHDChanging(string value);
    partial void OnTENHDChanged();
    partial void OnLOAIHDChanging(string value);
    partial void OnLOAIHDChanged();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    #endregion
		
		public HOA_DON()
		{
			this._KHACH = default(EntityRef<KHACH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENHD", DbType="NVarChar(15)")]
		public string TENHD
		{
			get
			{
				return this._TENHD;
			}
			set
			{
				if ((this._TENHD != value))
				{
					this.OnTENHDChanging(value);
					this.SendPropertyChanging();
					this._TENHD = value;
					this.SendPropertyChanged("TENHD");
					this.OnTENHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIHD", DbType="NVarChar(20)")]
		public string LOAIHD
		{
			get
			{
				return this._LOAIHD;
			}
			set
			{
				if ((this._LOAIHD != value))
				{
					this.OnLOAIHDChanging(value);
					this.SendPropertyChanging();
					this._LOAIHD = value;
					this.SendPropertyChanged("LOAIHD");
					this.OnLOAIHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Int NOT NULL")]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HOA_DON", Storage="_KHACH", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACH KHACH
		{
			get
			{
				return this._KHACH.Entity;
			}
			set
			{
				KHACH previousValue = this._KHACH.Entity;
				if (((previousValue != value) 
							|| (this._KHACH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH.Entity = null;
						previousValue.HOA_DONs.Remove(this);
					}
					this._KHACH.Entity = value;
					if ((value != null))
					{
						value.HOA_DONs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(int);
					}
					this.SendPropertyChanged("KHACH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH")]
	public partial class KHACH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAKH;
		
		private string _TENKH;
		
		private string _MATHUCUNG;
		
		private EntitySet<HOA_DON> _HOA_DONs;
		
		private EntityRef<THU_CUNG> _THU_CUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(int value);
    partial void OnMAKHChanged();
    partial void OnTENKHChanging(string value);
    partial void OnTENKHChanged();
    partial void OnMATHUCUNGChanging(string value);
    partial void OnMATHUCUNGChanged();
    #endregion
		
		public KHACH()
		{
			this._HOA_DONs = new EntitySet<HOA_DON>(new Action<HOA_DON>(this.attach_HOA_DONs), new Action<HOA_DON>(this.detach_HOA_DONs));
			this._THU_CUNG = default(EntityRef<THU_CUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKH", DbType="NVarChar(20)")]
		public string TENKH
		{
			get
			{
				return this._TENKH;
			}
			set
			{
				if ((this._TENKH != value))
				{
					this.OnTENKHChanging(value);
					this.SendPropertyChanging();
					this._TENKH = value;
					this.SendPropertyChanged("TENKH");
					this.OnTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCUNG", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MATHUCUNG
		{
			get
			{
				return this._MATHUCUNG;
			}
			set
			{
				if ((this._MATHUCUNG != value))
				{
					if (this._THU_CUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUCUNGChanging(value);
					this.SendPropertyChanging();
					this._MATHUCUNG = value;
					this.SendPropertyChanged("MATHUCUNG");
					this.OnMATHUCUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HOA_DON", Storage="_HOA_DONs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<HOA_DON> HOA_DONs
		{
			get
			{
				return this._HOA_DONs;
			}
			set
			{
				this._HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THU_CUNG_KHACH", Storage="_THU_CUNG", ThisKey="MATHUCUNG", OtherKey="MATHUCUNG", IsForeignKey=true)]
		public THU_CUNG THU_CUNG
		{
			get
			{
				return this._THU_CUNG.Entity;
			}
			set
			{
				THU_CUNG previousValue = this._THU_CUNG.Entity;
				if (((previousValue != value) 
							|| (this._THU_CUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THU_CUNG.Entity = null;
						previousValue.KHACHes.Remove(this);
					}
					this._THU_CUNG.Entity = value;
					if ((value != null))
					{
						value.KHACHes.Add(this);
						this._MATHUCUNG = value.MATHUCUNG;
					}
					else
					{
						this._MATHUCUNG = default(string);
					}
					this.SendPropertyChanged("THU_CUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = this;
		}
		
		private void detach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.KHACH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SANPHAM")]
	public partial class SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASP;
		
		private string _TENSP;
		
		private string _LOAISP;
		
		private string _HINHSP;
		
		private System.Nullable<int> _ThanhTien;
		
		private System.Nullable<System.DateTime> _NGAYSUDUNG;
		
		private System.Nullable<System.DateTime> _NGAYHETHAN;
		
		private EntityRef<CHITIETSANPHAM> _CHITIETSANPHAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASPChanging(string value);
    partial void OnMASPChanged();
    partial void OnTENSPChanging(string value);
    partial void OnTENSPChanged();
    partial void OnLOAISPChanging(string value);
    partial void OnLOAISPChanged();
    partial void OnHINHSPChanging(string value);
    partial void OnHINHSPChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    partial void OnNGAYSUDUNGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSUDUNGChanged();
    partial void OnNGAYHETHANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYHETHANChanged();
    #endregion
		
		public SANPHAM()
		{
			this._CHITIETSANPHAM = default(EntityRef<CHITIETSANPHAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASP
		{
			get
			{
				return this._MASP;
			}
			set
			{
				if ((this._MASP != value))
				{
					this.OnMASPChanging(value);
					this.SendPropertyChanging();
					this._MASP = value;
					this.SendPropertyChanged("MASP");
					this.OnMASPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSP", DbType="NVarChar(30)")]
		public string TENSP
		{
			get
			{
				return this._TENSP;
			}
			set
			{
				if ((this._TENSP != value))
				{
					this.OnTENSPChanging(value);
					this.SendPropertyChanging();
					this._TENSP = value;
					this.SendPropertyChanged("TENSP");
					this.OnTENSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISP", DbType="NVarChar(20)")]
		public string LOAISP
		{
			get
			{
				return this._LOAISP;
			}
			set
			{
				if ((this._LOAISP != value))
				{
					this.OnLOAISPChanging(value);
					this.SendPropertyChanging();
					this._LOAISP = value;
					this.SendPropertyChanged("LOAISP");
					this.OnLOAISPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHSP", DbType="NVarChar(20)")]
		public string HINHSP
		{
			get
			{
				return this._HINHSP;
			}
			set
			{
				if ((this._HINHSP != value))
				{
					this.OnHINHSPChanging(value);
					this.SendPropertyChanging();
					this._HINHSP = value;
					this.SendPropertyChanged("HINHSP");
					this.OnHINHSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSUDUNG", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSUDUNG
		{
			get
			{
				return this._NGAYSUDUNG;
			}
			set
			{
				if ((this._NGAYSUDUNG != value))
				{
					this.OnNGAYSUDUNGChanging(value);
					this.SendPropertyChanging();
					this._NGAYSUDUNG = value;
					this.SendPropertyChanged("NGAYSUDUNG");
					this.OnNGAYSUDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYHETHAN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYHETHAN
		{
			get
			{
				return this._NGAYHETHAN;
			}
			set
			{
				if ((this._NGAYHETHAN != value))
				{
					this.OnNGAYHETHANChanging(value);
					this.SendPropertyChanging();
					this._NGAYHETHAN = value;
					this.SendPropertyChanged("NGAYHETHAN");
					this.OnNGAYHETHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SANPHAM_CHITIETSANPHAM", Storage="_CHITIETSANPHAM", ThisKey="MASP", OtherKey="MASP", IsUnique=true, IsForeignKey=false)]
		public CHITIETSANPHAM CHITIETSANPHAM
		{
			get
			{
				return this._CHITIETSANPHAM.Entity;
			}
			set
			{
				CHITIETSANPHAM previousValue = this._CHITIETSANPHAM.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETSANPHAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETSANPHAM.Entity = null;
						previousValue.SANPHAM = null;
					}
					this._CHITIETSANPHAM.Entity = value;
					if ((value != null))
					{
						value.SANPHAM = this;
					}
					this.SendPropertyChanged("CHITIETSANPHAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THU_CUNG")]
	public partial class THU_CUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUCUNG;
		
		private string _TENTHUCUNG;
		
		private string _TUOITC;
		
		private string _GIOITINH;
		
		private string _LOAI;
		
		private string _HINHTC;
		
		private EntityRef<CHITIETTHUCUNG> _CHITIETTHUCUNG;
		
		private EntitySet<KHACH> _KHACHes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUCUNGChanging(string value);
    partial void OnMATHUCUNGChanged();
    partial void OnTENTHUCUNGChanging(string value);
    partial void OnTENTHUCUNGChanged();
    partial void OnTUOITCChanging(string value);
    partial void OnTUOITCChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnLOAIChanging(string value);
    partial void OnLOAIChanged();
    partial void OnHINHTCChanging(string value);
    partial void OnHINHTCChanged();
    #endregion
		
		public THU_CUNG()
		{
			this._CHITIETTHUCUNG = default(EntityRef<CHITIETTHUCUNG>);
			this._KHACHes = new EntitySet<KHACH>(new Action<KHACH>(this.attach_KHACHes), new Action<KHACH>(this.detach_KHACHes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUCUNG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUCUNG
		{
			get
			{
				return this._MATHUCUNG;
			}
			set
			{
				if ((this._MATHUCUNG != value))
				{
					this.OnMATHUCUNGChanging(value);
					this.SendPropertyChanging();
					this._MATHUCUNG = value;
					this.SendPropertyChanged("MATHUCUNG");
					this.OnMATHUCUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUCUNG", DbType="NVarChar(20)")]
		public string TENTHUCUNG
		{
			get
			{
				return this._TENTHUCUNG;
			}
			set
			{
				if ((this._TENTHUCUNG != value))
				{
					this.OnTENTHUCUNGChanging(value);
					this.SendPropertyChanging();
					this._TENTHUCUNG = value;
					this.SendPropertyChanged("TENTHUCUNG");
					this.OnTENTHUCUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUOITC", DbType="Char(5)")]
		public string TUOITC
		{
			get
			{
				return this._TUOITC;
			}
			set
			{
				if ((this._TUOITC != value))
				{
					this.OnTUOITCChanging(value);
					this.SendPropertyChanging();
					this._TUOITC = value;
					this.SendPropertyChanged("TUOITC");
					this.OnTUOITCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAI", DbType="NVarChar(30)")]
		public string LOAI
		{
			get
			{
				return this._LOAI;
			}
			set
			{
				if ((this._LOAI != value))
				{
					this.OnLOAIChanging(value);
					this.SendPropertyChanging();
					this._LOAI = value;
					this.SendPropertyChanged("LOAI");
					this.OnLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHTC", DbType="NVarChar(20)")]
		public string HINHTC
		{
			get
			{
				return this._HINHTC;
			}
			set
			{
				if ((this._HINHTC != value))
				{
					this.OnHINHTCChanging(value);
					this.SendPropertyChanging();
					this._HINHTC = value;
					this.SendPropertyChanged("HINHTC");
					this.OnHINHTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THU_CUNG_CHITIETTHUCUNG", Storage="_CHITIETTHUCUNG", ThisKey="MATHUCUNG", OtherKey="MATHUCUNG", IsUnique=true, IsForeignKey=false)]
		public CHITIETTHUCUNG CHITIETTHUCUNG
		{
			get
			{
				return this._CHITIETTHUCUNG.Entity;
			}
			set
			{
				CHITIETTHUCUNG previousValue = this._CHITIETTHUCUNG.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETTHUCUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETTHUCUNG.Entity = null;
						previousValue.THU_CUNG = null;
					}
					this._CHITIETTHUCUNG.Entity = value;
					if ((value != null))
					{
						value.THU_CUNG = this;
					}
					this.SendPropertyChanged("CHITIETTHUCUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THU_CUNG_KHACH", Storage="_KHACHes", ThisKey="MATHUCUNG", OtherKey="MATHUCUNG")]
		public EntitySet<KHACH> KHACHes
		{
			get
			{
				return this._KHACHes;
			}
			set
			{
				this._KHACHes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHes(KHACH entity)
		{
			this.SendPropertyChanging();
			entity.THU_CUNG = this;
		}
		
		private void detach_KHACHes(KHACH entity)
		{
			this.SendPropertyChanging();
			entity.THU_CUNG = null;
		}
	}
}
#pragma warning restore 1591
