CREATE DATABASE QUANLYTHUCUNG

CREATE TABLE THUCUNG2
(
	MATHUCUNG int not null primary key,
	TENTHUCUNG nvarchar(20),
	TUOITC char(5),
	GIOITINH nvarchar(3) not null,
	LOAI nvarchar(30),
)

CREATE TABLE KHACHHANG
(
	MAKH int not null primary key,
	TENKH nvarchar(20),
	MATHUCUNG int not null,
	CONSTRAINT FK_TC_KH Foreign key (MATHUCUNG) references THUCUNG2(MATHUCUNG)
)
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_TC_KH FOREIGN KEY (MATHUCUNG) REFERENCES THUCUNG2(MATHUCUNG)
--
INSERT INTO THUCUNG2 VALUES ('1',N'Lucky','4',N'Cái',N'Poodle')
INSERT INTO THUCUNG2 VALUES ('2',N'Na','6',N'Đực',N'Mèo Tam Thể')
INSERT INTO THUCUNG2 VALUES ('3',N'Lucy','10',N'Đực',N'Chihuahua')
INSERT INTO THUCUNG2 VALUES ('4',N'Đen','2',N'Cái',N'Alaska')
INSERT INTO THUCUNG2 VALUES ('5',N'Tom','1',N'Đực',N'Mèo Ba Tư')

INSERT INTO KHACHHANG VALUES ('01',N'Nguyễn Gia Bảo','4')
INSERT INTO KHACHHANG VALUES ('02',N'Lương Bích Hữu','5')
INSERT INTO KHACHHANG VALUES ('03',N'Hồ Văn Nam','1')
INSERT INTO KHACHHANG VALUES ('04',N'Đoàn Thế Phùng','3')